### ISSUE TITLE
Documentation: Context and Dependencies

### ISSUE THREAD

**Issue by iajrz** [pokt-foundation/pocket-e2e-stack#6]
The README should give users a leg up by stating:
* It depends on Docker Compose (and swarm mode in particular)
* It depends on the repos:
  * pokt-foundation/portal-api (aka gateway)
  * pokt-core/pocket-core (aka core)
  * pokt-network/pocket-js (aka client)
* How you can tell that the command is done and you can start working

**Comment by commoddity** [comment]
I incorporated this feedback into a PR #21 so I'm going to mark this issue as closed. Thanks for your input @iajrz .
